export const hdssData = {
  demographics: [
    {
      name: "Village A",
      population: 1200,
      birthRate: 22.4,
      deathRate: 7.8,
      medianAge: 28,
    },
    {
      name: "Village B",
      population: 950,
      birthRate: 18.7,
      deathRate: 8.2,
      medianAge: 32,
    },
    {
      name: "Village C",
      population: 1500,
      birthRate: 25.1,
      deathRate: 6.9,
      medianAge: 25,
    },
    {
      name: "Village D",
      population: 800,
      birthRate: 16.5,
      deathRate: 9.1,
      medianAge: 36,
    },
    {
      name: "Village E",
      population: 1100,
      birthRate: 20.3,
      deathRate: 8.0,
      medianAge: 30,
    },
  ],
  timeSeriesData: [
    { month: "Jan", births: 45, deaths: 22, migration: 12 },
    { month: "Feb", births: 38, deaths: 18, migration: 8 },
    { month: "Mar", births: 52, deaths: 25, migration: -5 },
    { month: "Apr", births: 43, deaths: 20, migration: 3 },
    { month: "May", births: 48, deaths: 23, migration: 7 },
    { month: "Jun", births: 50, deaths: 21, migration: -2 },
  ],
  ageDistribution: [
    { name: "0-4", value: 8.1 },
    { name: "5-14", value: 16.4 },
    { name: "15-24", value: 18.9 },
    { name: "25-44", value: 30.2 },
    { name: "45-64", value: 19.3 },
    { name: "65+", value: 7.1 },
  ],
  healthIndicators: [
    {
      village: "Village A",
      immunizationRate: 82,
      accessToWater: 76,
      malnutrition: 12,
    },
    {
      village: "Village B",
      immunizationRate: 78,
      accessToWater: 68,
      malnutrition: 15,
    },
    {
      village: "Village C",
      immunizationRate: 91,
      accessToWater: 85,
      malnutrition: 8,
    },
    {
      village: "Village D",
      immunizationRate: 74,
      accessToWater: 62,
      malnutrition: 18,
    },
    {
      village: "Village E",
      immunizationRate: 86,
      accessToWater: 79,
      malnutrition: 10,
    },
  ],
};
